default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  socket: /var/run/mysqld/mysqld.sock
  username: bikash
  password: mindfire

development:
  <<: *default
  database: rssnewsbasedb

test:
  <<: *default
  database: rssnewsbasedbtest

production:
  <<: *default
  database: rssnewsbasedbprod
